name: 'GitHub Action for Android Lint'
description: 'A tool to enforce Android style and conventions'
author: 'Yutaro Muta'
inputs:
  xml_path:
    description: 'The file path of the XML lint report produced by gradle. e.g `build/reports/*.xml`'
    required: true
  follow-symbolic-links:
    description: 'Indicates whether to follow symbolic links'
    default: true
runs:
  using: 'node12'
  main: 'dist/index.js'
branding:
  icon: 'check-square'
  color: 'green'
